# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv-matem.tex
          latexmk_use_xelatex: true
      - name: Install ghostscript
        run: sudo apt-get update --fix-missing && sudo apt install ghostscript
      - name: Change ImageMagick security policy
        run: |
          DQT='"' 
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read\|write${DQT} pattern=${DQT}PDF${DQT}"
          
          HGT="name=${DQT}height${DQT} value=${DQT}10KP${DQT}"
          HGTR="name=${DQT}height${DQT} value=${DQT}128Kp${DQT}"
          
          WDT="name=${DQT}width${DQT} value=${DQT}10KP${DQT}"
          WDTR="name=${DQT}width${DQT} value=${DQT}128Kp${DQT}"
          
          MAP="name=${DQT}map${DQT} value=${DQT}512MiB${DQT}"
          MAPR="name=${DQT}map${DQT} value=${DQT}4GiB${DQT}"
          
          MEM="name=${DQT}memory${DQT} value=${DQT}256MiB${DQT}"
          MEMR="name=${DQT}memory${DQT} value=${DQT}2GiB${DQT}"
          
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$HGT/$HGTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$WDT/$WDTR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MAP/$MAPR/" /etc/ImageMagick-6/policy.xml
          sudo sed -i "s/$MEM/$MEMR/" /etc/ImageMagick-6/policy.xml
      - name: Convert PDF to PNG
        run: convert -density 900 -background white -alpha off cv-matem.pdf -resize 25% -quality 90 -colorspace RGB cv-matem.png
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
